# Generated by Django 5.0.6 on 2024-06-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='imdbid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
