# Generated by Django 5.0.6 on 2024-06-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_content_imdbid_alter_content_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
